[package]
name = "shogai"
version = "0.1.0"
authors = ["bleuezm <michael.bleuez@grenoble-inp.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="*"
